### ISSUE TITLE
Formato Tarea 1 y Uso ChatGPT

### ISSUE THREAD

**Issue by vjuri23** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#1]
Holaa, estuve revisando el enunciado de la tarea, y noté que aparte de la extensión del archivo no se mencionan más características de formato, entonces ¿Es totalmente libre? Particularmente respecto al uso de Latex o Word, tamaño y tipo de letra, etcétera.

Además, quería saber si para la pregunta 1d. en que se debe interactuar con ChatGPT ¿Podemos usar otra IA, como Gemini? ¿O debe ser ChatGPT específicamente? Gracias de antemano.

**Comment by ignaciovilla** [comment]
Hola! El único requisito es que la extensión del archivo sea .pdf, y que este escrito en un programa computacional (Word, Latex, etc.), es decir, que no este escrito a mano. El resto del formato es libre-
Por otro lado, es necesario que sea ChatGPT.
Saludos.

**Comment by vjuri23** [comment]
Hola, gracias, pero ¿Estás seguro que solo chat GPT? Porque le pregunté al profe y me dijo que se podía usar otras IAs.

Saludos

**Comment by ignaciovilla** [comment]
En ese caso, puedes usar otras IAs.
Saludos
