### ISSUE TITLE
Tarea 2 - Ejercicio 3.2

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#10]
Tengo una duda respecto al predicado "conectados por n/3". Quiero asegurarme de que lo entendí correctamente:
1. Si tengo dos amigos y ambos están no visibles, entonces están conectados por "1"
2. Cuando mencionan que *todas las cadenas posibles* sean identificadas, para esto debemos ignorar ciclos, ¿no?
3. Todas las amistades de la cadena tienen que pasar por dos amigos no visibles, pudiendo quedar un camino más largo que si se fuera por amistades visibles.

**Comment by bernirosas** [comment]
1. Depende de si "tú" (X) es visible o invisible. Si eres visible, tu amistad con Y (por ejemplo) es visible, entonces conectados_por_n(X,Y,0) debe cumplirse (ya que no hay amistades no visibles). En caso contrario, tu amistad es invisible y debiese cumplirse conectados_por_n(X,Y,1).
2.

**Comment by bernirosas** [comment]
2. Sí, sino, en caso de ciclo habría "infinitas" proposiciones (siendo N el largo del ciclo) [conectados_por_n(X,Y,k), conectados_por_n(X,Y,k+N),conectados_por_n(X,Y,k+2N)], debes preocuparte nuevamente de eliminar ciclos.

**Comment by bernirosas** [comment]
3. La verdad no entiendo exactamente a lo que te refieres, la parte de cadena en la tarea se define antes que la parte de visibilidad
