### ISSUE TITLE
Tarea 2 Pregunta 2.1

### ISSUE THREAD

**Issue by Mikson16** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#11]
Hola, una consulta en la parte donde dice "demostrar que el programa..." con $\Pi = (p, \leftarrow p)$, ¿se debe entender que el programa contiene 2 "reglas" siendo la primera p. y la segunda :- p. ($\leftarrow p$)? Mi consulta va a que no entiendo bien si $\leftarrow p$ está representando :- p, que es lo que vimos en Clingo, es decir $\leftarrow$ apunta al vacío desde p.

**Comment by Mikson16** [comment]
Acabo de ver que se resolvió la duda en otra issue :3 perdón, graciaas

**Comment by ignaciovilla** [comment]
No hay problema, para la próxima revisa las issues anteriores para ver si alguna resuelve tu duda!
