### ISSUE TITLE
Tarea 2 Pregunta 3.2 sobre conectados_por_n/3

### ISSUE THREAD

**Issue by tcapom** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#12]
Tengo una duda con respecto al predicado conectados_por_n/3. Cuando se dice "existen dos usuarios conectados
a través de una cadena con exactamente n amistades no visibles", se refiere a que
1. La cadena de largo n tiene que estar compuesta exclusivamente por amistades no-visibles, o que
2. Una cadena de cualquier largo posea dentro de sí n amistades no-visibles.

Coloco como ejemplo el siguiente extracto de programa:

    amistad(a, b)
    amistad(b, c)
    amistad(c, d)
    visible(a)
    visible(d)

Se puede inferir que los usuarios b y c están ocultos, significando de que su amistad también estaría oculta.
No hay discusión en entender que `conectados_por_n(b, c, 1)` se cumpliría. Al mismo tiempo, entiendo que `conectados_por_n(a, d, 1)` también se cumpliría bajo la 2da interpretación, ya que existe una cadena entre a y d (del estilo a->b->c->d) y habría exactamente una amistad no visible (la de b con c).

Si me pueden aclarar esto, estaría agradecido.

**Comment by MaxAl100** [comment]
Pregunté en la ayudantía y dijeron que sí se puede pasar por amistades visibles entremedio, entonces el segundo caso es correcto. Aproveché de preguntar si los ciclos contaban y dijeron que no, es el n mínimo.

**Comment by ignaciovilla** [comment]
Hola! Como dice Max, la interpretación correcta es el segundo caso que planteas. Con respecto a los ciclos, la idea es que eviten contar infinitamente ciclos (parecido a la 3.1 👀)
Avísame si eso resuelve tu duda,
Saludos
