### ISSUE TITLE
Tarea 2 Pregunta 2.2

### ISSUE THREAD

**Issue by Mikson16** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#13]
Hola!

En la pregunta se pide "*demostrar que la propiedad de monotonía se cumple para programas en lógica sin negación, y sin reglas vacías*", mi duda es ¿Cuál es la propiedad de monotonía? No la he encontrado en la materia, ¿está en las diapositivas?

¡Muchas gracias, saludos!

**Comment by carlosiskindacool** [comment]
misma duda.

**Comment by bernirosas** [comment]
Hola! La única definición de monotonía que necesitan está en el enunciado.
Básicamente significa que si un modelo M pertenece a un programa II contenido en II' (Es decir, II tiene a lo más la misma cantidad de reglas que II', sin contar las excepciones del enunciado), entonces M se encuentra contenido dentro de un M' (es decir M contiene a lo más todas las proposiciones de tal M'). Deben demostrar que existe tal M'.
