### ISSUE TITLE
Tarea 2 Pregunta 3.1 

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#14]
Hola, en la pregunta 3.1 de la tarea 2 aparece lo siguiente: "Esto no significa que no debas considerar las amistades en un ciclo pero te
debes asegurar de tratar el problema que surge al tener ciclos en el grafo con ´unicamente los predicados
anteriores.". Esto significa que nuestra solución no debe tener mas predicados a parte de los ya definidos? es decir,  no se pueden proponer predicados auxiliares en nuestra solución?

**Comment by ignaciovilla** [comment]
Hola! La idea es que analices el problema que surge al usar el predicado `cadena(X,Y,Largo)` tal cual está definido en el enunciado. Luego de eso, la idea es que modifiques el predicado usando únicamente el comando `count`.
Avísame si eso resuelve tu duda,
Saludos

**Comment by gaspar-mr05** [comment]
Eso significa que no podemos crear otros predicados? O sea solo podemos modificar el predicado cadena? Y si es asi, puedo cambiar la aridad del predicado cadena?

**Comment by ignaciovilla** [comment]
Solo puedes modificar el predicado cadena y no puedes modificar su aridad. 
Saludos.

**Comment by carlosiskindacool** [comment]
igual, llevo muchos días pegado con este punto y no lo puedo resolver.

**Comment by ignaciovilla** [comment]
Hola! La idea es que solo modifiquen el predicado cadena, por lo que no sería del todo correcto crear otros predicados intermedios. Por otro lado, si pueden solucionarlo de dicha manera igualmente pueden obtener puntaje parcial.
Saludos
