### ISSUE TITLE
Tarea 2 - Parte 2. Duda notación

### ISSUE THREAD

**Issue by Pablo-Gonzalez-Calderon** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#15]
Buenas tardes, ✨

En la Parte 2 de la tarea, me surgieron un par de dudas de notación. Tengo entendido que en las reglas de la forma $Head \leftarrow Tail$, $Head$ y $Tail$ son _conjuntos de átomos proposicionales_. Por lo tanto, en el primer ejercicio, por ejemplo, $p$ y $q$ deberían ser conjuntos (de átomos proposicionales), ¿no? ¿O son átomos proposicionales como tal?

La verdad pregunto más que nada para trabajar con la notación correcta (discernir si ocupar $\in$ o $\subseteq$, o si debo encapsular en paréntesis de llaves $p$ y $q$, para trabajarlos como conjuntos). Y sé que probablemente me esté "ahogando en un vaso de agua", pero igual prefería saber jsjajsja 🍀

**Comment by Pablo-Gonzalez-Calderon** [comment]
Ahh okok, muchas gracias ✨

**Comment by ignaverb** [comment]
Hola! Y podría considerar a p. como $ p \leftarrow\emptyset$? Según yo se entiende la idea y ayuda a generalizar todo a expresiones del tipo $Head\leftarrow Body$

**Comment by ignaciovilla** [comment]
Para la pregunta 2.1 no se consideran reglas del tipo p←∅, aunque para las otras preguntas pueden ser consideradas según las condiciones especificadas en dichas preguntas.
Avísame si eso resuelve tu duda.

**Comment by ignaverb** [comment]
Hola! Me refería a que se pudiera pensar a p en el programa como una regla del tipo p←∅, lo hablé con el profesor hace poco y me dijo que sí, que esa era la manera formal de escribirlo matemáticamente. 

Muchas gracias igualmente por tu tiempo
