### ISSUE TITLE
Tarea 2 Pregunta 3.1

### ISSUE THREAD

**Issue by BenjaMartinezV** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#17]
Hola! Tengo dudas si en la pregunta 3.1 el modelo que resulta al hacer cadena/3 tiene que incluir todas las cadenas posibles o sea también las cadenas de largo 3, o si solamente hay que dejar las cadenas más cortas, por ejemplo si debemos incluir la cadena de largo 3 desde a Juan a Fernando que pasa por María y Elena o simplemente decir que esa cadena es de largo 1 por la amistad fernando Juan.

**Comment by bernirosas** [comment]
Sí, deberías considerar ambas cadenas en tu modelo. Lo mismo en el caso de conectados_por_n:)

**Comment by CrisDonosoMaass** [comment]
Entonces ,si meto un extra a las amistades Diego que sólo es amigo de Juan, entonces existe la cadena de largo 1 Diego -> Juan. Pero también debería contar la cadena 3 Diego->Juan->María->Juan?

**Comment by bernirosas** [comment]
Cuidado que ahí hay un ciclo (juan->maria, maria-> juan), así que no sería necesario que existan ambas. No importa si es que sí tomas esa cadena, pero importante manejar los ciclos porque sino clingo no puede manejar el modelo (ya que para clingo existen infinitos caminos entre maría y juan si es que no estableces lo contrario)

**Comment by CrisDonosoMaass** [comment]
> Cuidado que ahí hay un ciclo (juan->maria, maria-> juan), así que no sería necesario que existan ambas. No importa si es que sí tomas esa cadena, pero importante manejar los ciclos porque sino clingo no puede manejar el modelo (ya que para clingo existen infinitos caminos entre maría y juan si es que no estableces lo contrario)

Yaaa buenisimo gracias!
