### ISSUE TITLE
Tarea 2 Pregunta 3.1 - Que nos piden?

### ISSUE THREAD

**Issue by GSegov1a** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#18]
Hola,
No me queda muy claro que debemos hacer en esta sección, debemos implementar la solución en clingo o solo debemos proponer una solución.

**Comment by ignaciovilla** [comment]
Hola! Esto fue respondido en [esta issue](https://github.com/IIC2613-Inteligencia-Artificial-2024-2/Syllabus/issues/14).
Avísame si tienes dudas.
