### ISSUE TITLE
Tarea 2 como correr los test

### ISSUE THREAD

**Issue by AntonioEscobar01** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#19]
Hola, como se supone que tenemos que correr los tests para cada parte? Ya que los nombres dentro del enunciado y los archivos que entregan no son los mismos. Además, ¿Qué debería salir si esta correcto el output?

**Comment by ignaciovilla** [comment]
Hola! Los tests para la parte 4?

**Comment by ignaverb** [comment]
Hola! Me sumo a esta pregunta para la pregunta 4. Corro en la terminal 
clingo tests/testO1.lp DCCarrera.lp
y al hacer esto, me tira muchos errores del tipo, atom does not occur in any rule head: con baton(B) y con hurdleAdjacentToRobotToGoDown. Como puedo saber si mi parte 1 está bien? Se que se comenta que esos errores son normales, pero que tipo de output debería esperar entonces si está todo bien? 
También pensé en revisar con el otro comando, i.e, 
clingo DCCarrera.lp tests/O1.lp -c bound=12 | python3 process.py
pero obtengo el siguiente error que parece ser del process.py (no he tocado nada de los show ni de ese archivo)
answer.range_x = max(map(lambda x: get_number(x), list(filter(lambda x: "rangeX" in x, atoms))))
ValueError: max() arg is an empty sequence

Agradecería muchísimo si me pudieran ayudar con esto!

Saludos!
Ignacio!

**Comment by ignaciovilla** [comment]
Hola! Si el modelo no da una solución con todos los predicados indicados con el comando #show, entonces ` process.py` se cae. 
Para evitar los errores del tipo,`atom does not occur in any rule head: con baton(B)` pueden comentar los predicados y reglas de las secciones que no han implementado aún, lo que debería dejarles correr los tests de clingo sin el visualizador, usando el comando `clingo DCCarrera.lp tests/testO1.lp -c bound=12`.
Avísenme si eso les resulta,
Ignacio

**Comment by augustayanez** [comment]
ya intenté implementar todas las secciones de la pregunta 4 pero aún así me lanza errores del tipo "atom does not occur in any rule head" para todos los tests, por lo que me surgió la duda, ¿tenemos que crear las constantes nosotros para cada variable?

**Comment by lolenn10** [comment]
Hola!, he intentado correr el primer test (test01.lp) con todas las opciones que comentaron mas arriba y aun asi me sigue saliendo error. No he cambiado nada de ningun archivo, excepto de DCCarrera.lp la parte de la actividad 1. Lo demas lo comente todo. Agradeceria mucho si me pueden ayudar. Muchas gracias.
