### ISSUE TITLE
Tarea 2 Pregunta 3.2

### ISSUE THREAD

**Issue by lolenn10** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#20]
Hola! Tengo una duda con la pregunta 3.2. En esta pregunta, ¿Tenemos que ocupar lo hecho en la 3.1? (me refiero a ocupar el predicado cadena/3). O únicamente tenemos que hacer esa pregunta con amistad_visible/2 y conectados_por_n/3. Ademas de los predicados dados en la introduccion del problema.

Muchas gracias de antemano :)

**Comment by bernirosas** [comment]
Sí pueden usar el predicado cadena/3 y es recomendable
