### ISSUE TITLE
Tarea 2 Entregables Parte 4

### ISSUE THREAD

**Issue by vnloyola** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#21]
Hola! En el enunciado dice que solo se debe entregar `DCCarrera.lp` en el repositorio. Mi duda es si los demás archivos donde están los test y las imágenes se deben eliminar del repositorio, ya que en el base ya estaban arriba.

Gracias de antemano!

**Comment by FabriRandon** [comment]
No es necesario, lo que es importante es que entregues DCCarrera.lp con tu solución con las reglas implementadas.
