### ISSUE TITLE
Tarea 2 - 4.2 - Doble salto de hurdles?

### ISSUE THREAD

**Issue by CrisDonosoMaass** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#22]
Holis, estaba corriendo los tests de la parte 4.2 y me di cuenta que el test V5 tiene hurdles consecutivos, para este caso debería ser insatisfacible o un robot puede saltar más de uno a la vez?

**Comment by bernirosas** [comment]
Se debería poder satisfacer!

**Comment by CrisDonosoMaass** [comment]
Graciaas!
