### ISSUE TITLE
Tarea 2 Pregunta 3.3

### ISSUE THREAD

**Issue by 1982739** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#23]
Tengo una consulta sobre la 3.3 de la tarea. Preguntan por la ruta con menos amistades ocultas, pero, ¿tengo que entregar la con menos amistades ocultas de todo el modelo, o de cada amistad en el modelo?. Porque si fuese la segunda, eso es básicamente la 3.2, ¿o me equivoco?

Muchas gracias

**Comment by bernirosas** [comment]
Hola! Debes entregar la cadena mínima para cada conectados_por_n/3. Es diferente a la 3.2 ya que te piden la cadena mínima mientras la 3.2 pide todas las cadenas sin considerar ciclos. Saludos
