### ISSUE TITLE
Tarea 2 parte 4

### ISSUE THREAD

**Issue by LukasCarvallo** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#24]
Hola!! Tengo un problema cuando ejecuto el testfull, el problema que me sale que es del rango x, función que viene predefinida en el código y cuando lo veo en la pagina los robots pasan por encima de los obstáculos, funciones que venían predefinidas para que no pase.
Junto a lo anterior seria muy útil si podrían mostrar una capsula de como se debería ver en la pagina el funcionamiento correcto (no código)

**Comment by bernirosas** [comment]
Hola! No sé que está mal con tu código pero ese test fue probado con la solución y funciona, asegúrate de que estes colocando el bound correcto. En cuanto a lo segundo, no me parece que sea necesario en cuanto sigas correctamente las instrucciones del enunciado ya que el movimiento de los robots es bastante sencillo (a excepción quizás del salto de vallas pero por ello mismo fue descrito en cuanto a tiempos en el enunciado). Si tienes dudas con respecto a cómo alguna otra acción se debiese ver, puedes preguntar. Saludos
