### ISSUE TITLE
Tarea 2 Pregunta 4 - Sobre los bounds de los problemas

### ISSUE THREAD

**Issue by tomas-jackson** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#26]
Al ejecutar los test cases, deberiamos tomar los bounds entregados en los test cases como el minimo posible de pasos necesarios para que el programa sea correcto y satisfacible?. Dicho de otra manera, si tengo un programa que es satisfacible en menos pasos que el bound (por ejemplo, 11 en vez de 12), entonces este esta incorrecto y hay alguna regla que no esta bien implementada?

Gracias

**Comment by bernirosas** [comment]
Hola! Es probable que el ayudante que hizo tal test no haya revisado que se podía hacer en un bound menor. No te preocupes, mientras que tu robot en la visualización se vea bien, todo bien. Si quieres estar seguro dime que test es para revisar.

**Comment by tomas-jackson** [comment]
Entiendo, muchas gracias por tu respuesta :D. Mi problema es el test B4 que me entrega un modelo con bound minimo de 11 en vez de 12, y es el unico de todos los tests donde pasa eso.

**Comment by bernirosas** [comment]
Confirmo que el bound 11 también es válido! Un errorcito que se pasó

**Comment by tomas-jackson** [comment]
Vale. muchas gracias! c:
