### ISSUE TITLE
Tarea 2 pregunta 3.2

### ISSUE THREAD

**Issue by nicolaslindl** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#27]
Tengo una duda respecto al predicado conectados_por_n/3 :

Si tengo 
amistad(a, b).
amistad(b, c).
amistad(c, d).
visible(a).
visible(b).

El predicado conectados_por_n/3 bien implementado debería entregar:
conectados_por_n(a, b, 0)  ->  por cadena(a, b, 1), donde amistad(a, b) es visible
conectados_por_n(a, b, 2)  -> por cadena a->b, b->c, c->b, b->a, donde amistad(b, c) y amistad(c, b) son invisibles
conectados_por_n(a, b, 4)  -> por cadena a->b, b->c, c->d, d->c, c->b, b->a, donde amistad(b, c), amistad(c, d), amistad(d, c), amistad(c, b) son invisibles

y así sucesivamente para todas las combinaciones de nodos que tengan cadena entre sí?
O entendí mal el enunciado?

**Comment by ignaciovilla** [comment]
Hola, según el ejemplo dado, conectados_por_n(a, b, 0) efectivamente debe estar.
Luego, en este caso amistad_visible(b,c) si debe estar en la red, ya que b es visible y tiene amistad con c, por lo que existirá conectados_por_n(a, b, 1) por a->b, b->c, c->b, b->a. 
Siguiendo la misma lógica, conectados_por_n(a, b, 2) también estará, pero no por lo que mencionas anteriormente, sino porque existe conectados_por_n(a, d, 1) y conectados_por_n(d, b, 1) entonces existirá conectados_por_n(a, b, 2).
Y luego conectados_por_n(a, b, 4) no debe estar porque no existe una cadena de largo 4.
Avísame si eso responde tu duda

**Comment by JManuelJouanne** [comment]
Hola!! Acá creo que no estoy entendiendo cuál es el límite del largo de las cadenas ¿Por qué la cadena puede devolverse pero no puede hacer ida-vuelta-ida?¿Qué es lo que limita el largo? ¿Para esta pregunta debemos seguir utilizando el predicado de cadena/3? Yo ya no lo estaba usando.
Lo otro es que con el ejemplo sería
a --(visible)-- b --(visible)-- c --(invisible)-- d
por lo que creo que NO estaría conectados_por_n(a,b,1). O por lo menos a mi no me calza.

**Comment by carlosiskindacool** [comment]
yo no entiendo por qué conectados_por_n(a,b,1) no debería existir. eso significa que en el ejemplo dado (con a y b visibles) sería correcto conectados_por_n(a,b,0) en vez de n = 1?
otra duda que tengo es si se considera válida una cadena que tiene miembros que se repiten, ejemplo con la cadena a-b-c de largo 3 y la cadena c-b de largo 1, sería válido concluir la cadena a-b de largo 3?
