### ISSUE TITLE
Tarea 2 P3 - Ciclos

### ISSUE THREAD

**Issue by rodridelafuente** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#28]
Hola! Tengo una duda sobre los ciclos que se pueden formar en cada parte de la pregunta 3.
En el enunciado nos dan un ejemplo donde se conecta a fernando y juan, conectando al primero de la cadena con el último. Puede pasar que se formen ciclos entre otros miembros de la cadena? o solo puede ser entre el primero y el último?.
Por ejemplo, puede pasar algo de este estilo?
amistad(juan,maria).
amistad(maria,elena).
amistad(elena,fernando).
amistad(fernando,maria).

**Comment by ignaciovilla** [comment]
Hola! Si, pueden haber ciclos de cualquier tamaño dentro de los problemas, por lo que el ciclo que propones es válido.
Avísame si eso resuelve tu duda.

**Comment by rodridelafuente** [comment]
me queda claro, muchas gracias :)
