### ISSUE TITLE
Duda pregunta 2 b) Tarea 1

### ISSUE THREAD

**Issue by Mikson16** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#3]
Cuando se pegunta por las áreas de la IA vista en clases, ¿Se refiere a las sub áreas descritas en la diapositiva 4 de la clase 2? O a otra área?

Adjunto una imagen de la diapositiva:
![image](https://github.com/user-attachments/assets/07b24101-6a54-4038-997c-4ce8ba371951)

**Comment by ignaciovilla** [comment]
Hola! 
Si, se refiere a las 5 que aparecen en esta diapositiva.
Saludos
