### ISSUE TITLE
Tarea 2 P3.2

### ISSUE THREAD

**Issue by Ikilly0** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#30]
Como podemos separar la propiedad amistad(X,Y) :- amistad(Y,X) entre la P3.1 y la P3.2? apenas incluyo esta propiedad, si la incluyo despues, me genera conflicto en el programa.

**Comment by ignaciovilla** [comment]
Puedes generar dos archivos distintos, uno que la contenga y otro que no.
Avísame si eso resuelve tu duda.
