### ISSUE TITLE
Error al intentar generar output.txt parte 4

### ISSUE THREAD

**Issue by augustayanez** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#34]
Hola! Cuando intento generar el archivo output.txt, me lanza el siguiente error que no se como arreglar:

clingo DCCarrera.lp tests/testfull.lp -c bound=12 | py process.py

Traceback (most recent call last):
  File "C:\Users\augus\Desktop\inteligencia artificial\t2-2024-2-augustayanez\Parte4\process.py", line 72, in <module>
    answer.range_x = max(map(lambda x: get_number(x), list(filter(lambda x: "rangeX" in x, atoms))))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence

**Comment by FabriRandon** [comment]
Puede ser que quizás no te esté encontrando una solución. Te sugiero partir depurando sin el | py process.py de manera que solo ejecutes el código de clingo, probablemente te ayude comenzar por ahí para encontrar tu error.
Saludos.
