### ISSUE TITLE
Citar 

### ISSUE THREAD

**Issue by CarlangaUC** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#35]
En torno a la parte 3 y 4 como no hay entregable de partes pdfs ( al menos para 3.2, 3.3 y toda la 4), como puedo citar codigo o consultas que se pudo hacer a chatGPT ?

**Comment by ignaciovilla** [comment]
Hola, el programa detalla lo siguiente:
"El uso de agentes inteligentes como ChatGPT, Gemini o Copilot, est´a permitido en las tareas siempre
y cuando se indique, al inicio de la respuesta, que s´ı se utilizaron, que se especifique de
manera clara su uso (al menos el prompt y respuesta) y que las respuestas de estos sean
modificadas sustancialmente."
Avísame si eso resuelve tu duda

**Comment by CarlangaUC** [comment]
Como puedo mostrar lo que me comentas si no hay parte escrita por ejemplo en alguna parte de solo codigo, simplemente muestro lo que pregunte y respondio en el mismo codigo?
