### ISSUE TITLE
Tiempos y dirección en 4.2 T2

### ISSUE THREAD

**Issue by Arielmild** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#37]
Hola,
Primero que todo, creo que no me queda claro el tema de los tiempos para la actividad 2 de la pregunta 4. ¿Es correcto usar una notación del estilo: T cuando el robot está adyacente a una valla (se ejecuta jump), T+1 cuando está sobre la valla y T+2 para cuando avanza a la siguiente casilla y ejecuta getdown?

En segundo lugar, ¿Es necesario definir la dirección en la que el robot está avanzando un robot luego de saltar una valla o esta ya viene "heredada" del salto?

De antemano,
gracias.

**Comment by bernirosas** [comment]
Hola! En T+1 se ejecuta la acción getDown pero en T+2 el robot ya cruzó la valla (es decir la acción getDown toma efecto un tiempo después).
La segunda pregunta no entiendo muy bien a qué te refieres, debes poner en tu regla lo que creas necesario y no puedo ayudarte con ello, con que funcione el programa según el enunciado, está bien hecha la regla. 
Saludos.
