### ISSUE TITLE
Consulta materia CL1

### ISSUE THREAD

**Issue by ignaverb** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#38]
Hola!
Tengo un par de preguntas que me surgieron estudiando para el CL1, agradecería mucho si me pudieran ayudar, estas son, 

-Se puede tener más de un estado final? En ese caso como se definiría h(s), la estimación debe ser respecto a cual estado final?

-En el ejercicio 8 de la guía, por qué se tiene la siguiente solución?
1 {defectuosa(C) : componente(C)} 1.
observacion :- val(o1,1),val(o2,0).
:- not observacion.

Se estaría escogiendo correctamente el componente defectuoso con 1 {defectuosa(C) : componente(C)} 1.? Según yo se generan diversos modelo, no veo como se estaría viendo el componente defectuoso. O acaso se busca otro objetivo con la respuesta?

Desde ya gracias!

**Comment by ignaciovilla** [comment]
Hola! 
Con respecto a la primera pregunta, puedes asumir que solo existe un estado final.

Por otro lado, entiendo que la pregunta es con respecto al ejercicio de la guía 5. En ese caso, se agregan dichas reglas porque no sabemos cual de los componentes es el que esta fallando (solo 1), entonces al agregar la regla 1 {defectuosa(C) : componente(C)} 1, queremos modelar dicho comportamiento, es decir, que haya exactamente un componente malo. Esto nos generará más de un modelo, donde cada uno tendrá un componente que falla.
Ahora, hay algunos modelos que no nos servirán porque puede ser que un componente este defectuoso pero aún así el circuito nos entregue la respuesta correcta o no la combinación que queremos (un 1 en
o1 y un 0 en o2), por lo tanto filtramos todos los modelos que no tienen este resultado final usando las reglas observacion :- val(o1,1),val(o2,0). y :- not observacion., en donde observacion sería la combinación un 1 en
o1 y un 0 en o2 que estamos buscando.

Avisame si eso resuelve tu duda.

**Comment by ignaverb** [comment]
Muchísimas gracias!
Me quedó todo claro.
Si no te es molestia, me podrías ayudar con una última cosa, en clases vimos como realizar una reducción para un programa con negación, vimos el caso en que Neg ∩ X = ∅ y el caso en que Neg ∩ X != ∅, pero que pasaría si mi regla es del tipo, Head<- pos U not(neg_1)U not(neg_2), donde  neg_1 ∩ X = ∅ y neg_2 ∩ X != ∅, que se debe hacer en este caso mixto?
