### ISSUE TITLE
Tarea 3 P2 Act4 -  Sobre testear sin primitiveStraight ni primitiveDiagonal

### ISSUE THREAD

**Issue by tcapom** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#39]
Hola! Estoy teniendo un problema con la pregunta 2 actividad 4, en la que al intentar programar `primitiveStraight` y `primitiveDiagonal` los resultados me salían insatisfacibles, tal como aparecen en la imagen.

![image](https://github.com/user-attachments/assets/42c44c37-9831-4a58-b3c2-fea7393ecced)

Ahora, lo que me causó curiosidad de esto, es que en todos los casos se revisó un solo nodo y no se expandió más. Al revertir el progreso de `primitiveStraight` y `primitiveDiagonal` y dejarlas vacías, el resultado sigue siendo el mismo. En mi concepción de las State Lattices, había entendido de que las primitivas `primitiveRightAngle` y `primitiveDiagonalAngle` iban a funcionar igualmente dentro de los conjuntos de primitivas a los que pertenencen, y aunque no fueran suficientes para garantizar llegar al objetivo, igualmente ser capaces de expandir la Open con los nodos accesibles asignados por `primitiveRightAngle` y `primitiveDiagonalAngle`, los cuales no deberían ser cero (al menos mientras el agente no spawnee en un espacio estrecho).

Cualquier ayuda es agradecida.

Por si es contextualmente necesario, las actividades anteriores sí me han resultado, y la configuración de ejecución que usé es la siguiente.

![image](https://github.com/user-attachments/assets/da2155af-4409-4d95-963e-2127401601df)

**Comment by GonzaloFuentes1** [comment]
¡Hola!

El problema es que dada la implementación hecha si no encuentra solución el problema no retorna el nodo que se puede rastrear para encontrar el camino (revisa `test_map.py`, si no encuentra camino decimos que el costo es -1 para decir que no hay camino). En relación a lo segundo que mencionas, las primitivas `primitiveRightAngle` y `primitiveDiagonalAngle` son demasiado restrictivas para encontrar caminos de manera sencilla, puesto que solo son movimientos curvos (en el visualizador se pueden ver que son medios diagonales, pero es por aproximación del visualizador). Por eso, **deben** implementar `primitiveStraight` y `primitiveDiagonal` para que ustedes llamen a `primitiveSimpleRight`, `primitiveSimpleDiagonal`  y  `primitiveFull`. 

Como comentario, en la actividad 4 aún no tienes que probar los State Lattices, debido a que tienes que desarrollar la actividad 5 para revisar los vecinos. En la actividad 4 solo están creando las primitivas.

Quedo atento a tus comentarios y mucho ánimo con la tarea!

**Comment by tcapom** [comment]
Vale gracias! 👍
