### ISSUE TITLE
Duda Formato citas Tarea 1

### ISSUE THREAD

**Issue by ignaverb** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#4]
Hola!
Una consulta, para el uso de fuentes en la tarea 1 existe algún formato de cita específico que debamos usar? O basta con que coloquemos los urls correspondientes y en que pregunta se utilizan?
Y para la pregunta 2a) se puede citar? asumí que sí pero de todos modos prefiero preguntar para asegurarme

Saludos y gracias desde ya!

**Comment by ignaciovilla** [comment]
Hola! Mientras sigas el mismo formato para todas las citas, y se entienda de donde extrajiste la información está bien. Por otro lado, para la 2)a) puedes citar.
Saludos.
