### ISSUE TITLE
Parte 2 actividad 1

### ISSUE THREAD

**Issue by lolenn10** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#42]
Hola, estoy haciendo la actividad 1 de la parte 2, en la que solo hay que implementar las heurísticas. Eso fue lo único que hice, pero al momento de probar algún test, por ejemplo con el mapa simpleton.map el auto empieza y termina donde quiere. No he tocado nada mas del código que no sean las funciones de las heurísticas en map.py. Esta bien que sea así por que no he implementado nada mas, o esta mal?
![hola](https://github.com/user-attachments/assets/647480d8-a9cb-4201-980f-a286769a1d30)
![image](https://github.com/user-attachments/assets/be08f4e2-9ac6-4724-b75d-1fee336ac5b4)

**Comment by GonzaloFuentes1** [comment]
¡Hola! 

Lo que pasa es que los cubos de arriba son posiciones de referencia para un posible problema estándar (mira los archivos .map y tienen un I y G para hacer testeos, se nos fue eliminarlos para evitar la confusión). 

El código está hecho para que las posiciones iniciales y finales sean aleatorias (igual que la pose inicial que tienen para la parte de las primitivas). Al definir la semilla en `random.seed(0)` los problemas los nodos de inicio y final deberían ser constantes. 
Por lo que veo a simple vista se ve bien implementado.

Quedo atento a tu comentario!
