### ISSUE TITLE
Epsilon en primitiveSimple y diagonal

### ISSUE THREAD

**Issue by CrisDonosoMaass** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#43]
Hola! Estaba probando mi código y me entró la duda si las primitivas simples y diagonales debían sumarle el costo de epsilon o si es sólo para las angle. Muchas gracias!

**Comment by GonzaloFuentes1** [comment]
¡Hola!
El costo epsilon es solo para las con angle.

Saludos!
