### ISSUE TITLE
Tarea 3 Pregunta 2 actividad 1 int has no len()

### ISSUE THREAD

**Issue by Mikson16** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#44]
Al intentar ejecutar test_map.py, siguiendo las instrucciones del enunciado, la terminal tira el error "TypeError: object of type 'int' has no len()"
![image](https://github.com/user-attachments/assets/b5c7f08e-c27b-446d-b37d-cce17d85a185)

**Comment by GonzaloFuentes1** [comment]
¡Hola!

Se me puede ocurrir que pueden ser varios errores ¿Revisaste que el algoritmo elegido ya está implementado? puede ser que estas ejecutando "EarlyAstar" sin haberlo implementado ¿Puedes mandar un pantallazo de la configuración que le das para revisarlo a fondo?

¡Quedo atento a tus comentarios!

**Comment by Mikson16** [comment]
Al parecer si era el caso donde se ejecuta EarlyAstar, pero ahora me aparece el error AttributeError: 'NoneType' object has no attribute 'trace', lo único que he modificado son las funciones de las distancias euclidean, manhattan y octile de map.py, creo que hay una issue sobre este problema.

De todas formas gracias por la respuesta!

**Comment by GonzaloFuentes1** [comment]
Si lo único que has implementado son las heurísticas cuidado con estar usando las primitivas. Las tienes que implementar más adelante.

Saludos!

**Comment by Mikson16** [comment]
La respuesta al problema era ingresar la heurística como una función, para que se guarde en el atributo,, el problema era que estaba ingresando la función de la heurística evaluada en vez de la función sola.

Muchas gracias de todas formas!!!

**Comment by CarlangaUC** [comment]
Hola!

Termine presentando el mismo problema asociado a "AttributeError: 'NoneType' object has no attribute 'trace'" , si pueden explicar como se puede replantear para solucionar este problema agradecido.
