### ISSUE TITLE
Tarea 3 - Pregunta 1 (Línea 13, pseudocódigo Early A*)

### ISSUE THREAD

**Issue by vjuri23** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#45]
Hola, quería saber si la línea 13 (U <- f(v)) del código de Early A* está escrita correctamente, y de ser así, ¿qué valor se encuentra en f(v) en ese instante? Lo pregunto, porque la definición de f(v) ocurre en la línea 16 (posterior a asignación de U ), y no existe un valor inicial para f(v) con v != s0. Así, quería saber si querían referirse a g(v) (U <- g(v)), o si hay algo que no estoy considerando. Gracias de antemano. Adjunto imagen sección código: 

![image](https://github.com/user-attachments/assets/06b9684e-acb3-4efc-96be-0eb90f00a6bb)

**Comment by Mikson16** [comment]
Tengo una duda similar, también sobre el algoritmo, porque no sé si funciona en todos los casos, por ejemplo si tengo una estructura de 1 solo nodo, u, este no tiene sucesores, por lo cual no entra en el ciclo for y como ya no hay elementos en Open, sale del while sin retornar nada porque U sigue siendo infinito y el costo de f(u) es menor que U, no sé si estoy bien, pero creo que el pseudocodigo no cumple con los requerimientos de correctitud.
Ya que, por ejemplo si tengo un árbol de 3 nodos, con u como raíz y el segundo nodo hijo de u como objetivo, el valor de U no se actualiza dentro del ciclo a menos que v sea objetivo, es decir que cuando se salga del primer hijo y se siga al segundo hijo de u, el valor de U seguira siendo infinito, g(v2), valdrá infinito por la condición inicial del algoritmo, se entra en la línea 11 y se tendrá un g(v2)= inf < U= inf, como eso no está bien determinado, no se determina sol, no se determina un nuevo valor de U y se sigue sin retornar nada.
Es posible que esté equivocado porque no estoy entendiendo el algoritmo, pero por más que lo analizo, siento que el pseudocodigo presentado, no funciona correctamente.

**Comment by GonzaloFuentes1** [comment]
Hola!

Efectivamente hay un error en la línea 13. Debería ser g(v) <- U. Se mandará un anuncio para todos.

Saludos.
