### ISSUE TITLE
Tarea 3 Pregunta 2, Uso del codigo

### ISSUE THREAD

**Issue by chocolito24** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#47]
Hola buenas! Estoy recién comenzando la pregunta 2, e implementé solamente las funciones heurísticas en map.py. Al momento de correr el código, con las siguientes variables:
![image](https://github.com/user-attachments/assets/e62dfa17-425a-4ffa-a22a-3093a9a25154)
Me aparece el siguiente error:
\DCCarrera\test_map.py", line 87, in <module>
    path = [(int(c.x), int(c.y)) for c in result.trace()]
AttributeError: 'NoneType' object has no attribute 'trace'
Tengo entendido que result es el resultado de usar el algoritmo de búsqueda establecido (en este caso A*). Se supone que no debemos modificar A* entonces no se de donde puede venir el problema. Probé también usando las heurísticas que definí, y aparece el mismo error.
Pensé que podría tener que ver con estar tratando de usar primitivas no definidas, por lo que también lo corrí con los siguientes atributos:
![image](https://github.com/user-attachments/assets/c114cac8-7411-4eec-a4f3-c3c4488e8afb)
Y me aparece "conectividad no soportada":
![image](https://github.com/user-attachments/assets/d1c75832-a275-4943-ba3b-8b36754cf88b)

Supongo que el problema es que no estoy entendiendo cómo usar el código, asique quedo atento por si me pueden ayudar. Muchas gracias!

**Comment by chocolito24** [comment]
La otra duda que me surge, es que nos piden comparar el número de expansiones (nodos abiertos y nodos generados), el tiempo de cómputo y el costo del camino obtenido, según la heurística utilizada. El algoritmo A* descrito en el archivo, solo retorna el nodo solución, por lo cual como deberíamos hacer para obtener el tiempo de cómputo de A* y el número de expansiones? O está implementado en alguna otra parte?

**Comment by GonzaloFuentes1** [comment]
¡Hola!
Con respecto a lo primero es porque `connectivity` debe ser igual `int(4)` (o 4), no el string `"int(4)"`. Respecto a lo segundo, cuando termina de calcular el camino el programa hace un `print` de justamente lo pedido.

¡Saludos y éxito con la tarea!

**Comment by Arielmild** [comment]
> ¡Hola! Con respecto a lo primero es porque `connectivity` debe ser igual `int(4)` (o 4), no el string `"int(4)"`. Respecto a lo segundo, cuando termina de calcular el camino el programa hace un `print` de justamente lo pedido.
> 
> ¡Saludos y éxito con la tarea!

Hola, tengo el mismo problema del primer error. Entiendo lo que explicas sobre el int y el string, pero no entiendo cómo arreglarlo directamente, por si lo podrías explicar por favor.

**Comment by Delta-9001** [comment]
Hey hello Mr.Chocolito, I just fount it is at the output.Json, you need to pull to bottom of the code, and you will find there are "cost": 
 "expansions": 
 "generated": 
 "runtime": 
to describe what we need, but I really wonder to know how could we do the comparison.
@chocolito24

**Comment by Delta-9001** [comment]
Hello, I got a problem, I found that after I run the test_map, there is nothing new generated, the result in the file output.json remain the initial value, so I wonder is there any fix for that.

**Comment by Delta-9001** [comment]
I think I finally fixed that, but still can not update the output.json file. I run the code in a jupyter file then get the result
![1728761112762](https://github.com/user-attachments/assets/74915872-6195-4a50-9a30-aa687dbd89bc)

**Comment by vale1206** [comment]
Hola, tuve el mismo problema del trace y le cambie a int(4). Pero ahora en consola imprime muchas cosas (creo que puede ser el mapa) y no se si tengo que esperarlo o se me queda pegado en un loop

**Comment by Delta-9001** [comment]
Hey hello, I think I misunderstand something, first is there is a missiing in my module of my python, so I used cmd "pip install termcolor" to fix that, then the output of test_map.py will directly showed in the terminal window, it's like what I did, hope this can help you, if there is anything new and relevant to this topic I find, I will post it at here.
![1729004943012](https://github.com/user-attachments/assets/0dda3518-b9c2-4a94-87a1-8c2b36d1a01b)

**Comment by Delta-9001** [comment]
Hice una revisión sobre esta actividad, lo primero es ir a map.py para terminar el contenido de esos algoritmos heurísticos, segundo es elegir el mapa diferente en la zona "Variables configurables" de test_map, tercero es seleccionar la conectividad como 4 (esto está preprogramado, no necesitamos modificar nada), cuarto es activar el algoritmo heurístico en la zona de configuración. Finalmente, ejecútalo, luego podrás ver que se generó el mapa en tu terminal y la salida que necesitamos para el informe.

**Comment by Delta-9001** [comment]
Hola, perdón por molestarte de nuevo. Acabo de descubrir que mi test_map.py carece de una oración crítica en la parte de la lógica de ejecución principal. Su función es calcular el costo del algoritmo. Si queremos generar este valor, debemos agregar una oración en la parte "si resulta", la agrego en la posición deseada y este es el efecto. Espero tener razón y que pueda ayudar a cualquiera que tenga la misma confusión que yo.
![1729032942018](https://github.com/user-attachments/assets/f78666df-03f0-49b8-a973-ba32d00763de)
