### ISSUE TITLE
Rotar y moverse para agente en Actividad 5

### ISSUE THREAD

**Issue by NachoRinda** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#51]
Hola, tengo una duda acerca del movimiento y pose en primitiveStraight y primitiveDiagonal. ¿Puede el agente rotar y moverse? Es decir, si está mirando hacia al frente, ¿es válido que rote su pose hacia atrás y avance hacia atrás mismo?, todo dentro de una de estas primitivas.

**Comment by GonzaloFuentes1** [comment]
Hola!

Las primitivas `primitiveStraight` y `primitiveDiagonal` solo hacen que al estar mirando en una pose puedan moverse al frente. Para "rotar" el auto tiene que ir variando la pose con las primitivas que les pasamos que hacen movimientos curvos, por lo que es necesario que se preocupen por eso.

Saludos!

**Comment by NachoRinda** [comment]
Ok, ¿pero que pasa si el agente queda mirando hacia un muro? En ese estado no puede avanzar de ninguna manera pues las rotaciones que hay implican que se avance para girar y, en algunos casos, se queda sin sucesores pues no existe primitiva que le deje rotar sobre sí mismo. No me queda claro si de esta forma siempre encuentre la solución y mi implementación falla así en muchos casos.

**Comment by GonzaloFuentes1** [comment]
Hola!

Es parte de la tarea observar este tipo de problemas. Por eso les decimos en el enunciado que tengan cuidado si no resuelven todos los problemas.

Saludos!
