### ISSUE TITLE
Pregunta 2 Actividad 1

### ISSUE THREAD

**Issue by CarlangaUC** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#52]
Hola!

Sucede que estuve intentando debugear una parte asociada a las heuristicas y encontre que en una parte del codigo se hace referencia a un atributo "p" de las celdas, queria saber que es y como es que lo buscaria leer el programa ya que me arroja error . Adjunto el mensaje de error.

"DCCarrera\test_map.py", line 81, in <listcomp>
    path = [(int(c.x), int(c.y), c.p) for c in result.trace()]
AttributeError: 'Cell' object has no attribute 'p'"

Especificamente en la linea 81 osea:

![image](https://github.com/user-attachments/assets/eeb7cd18-ae5a-4c94-8f56-0522633cfd9d)

**Comment by GonzaloFuentes1** [comment]
Hola!

Ese atributo `p` hace referencia a la pose que está teniendo en un instante del camino.

Saludos.
