### ISSUE TITLE
Tarea 3 - P2 - Actividad 1

### ISSUE THREAD

**Issue by tomas-jackson** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#54]
Cuando nos piden crear una tabla con el numero de expansiones, el tiempo de computo y el costo, se refiere a los valores acumulados de las 10 ejecuciones? O es esos valores pero en solo una de las ejecuciones?

Otra duda, debemos poner el numero de expansiones o el numero de generados y el numero de abiertos?

Espero su respuesta, gracias! =]

**Comment by GonzaloFuentes1** [comment]
Hola!

Pueden hacer las dos opciones, la idea es que vean el comportamiento en general de las heurísticas. Ahora por obvias razones de dejarlo más bonito hay una forma más clara de hacerlo.

Saludos!

**Comment by GonzaloFuentes1** [comment]
Con respecto a lo segundo, indica todo lo entregado. Para que así tengas un análisis completo.
