### ISSUE TITLE
Pregunta 3 - Actividad bonus

### ISSUE THREAD

**Issue by LuNov4** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#56]
Holaa, una pregunta respecto a la función de evaluación de la pregunta extra, si mi evaluación creada en la actividad 4 también cumple los criterios de la actividad extra, puedo sólo probar que los cumple para obtener el bonus? o necesariamente debo crear una nueva?

Graciass

**Comment by balliende** [comment]
Hola!
Si tu función de evaluación de la actividad 4 cumple con los requisitos del bonus, no es necesario crear otra. Puedes utilizar la misma función, pero igual responde las preguntas de manera separada, contestando lo que te pide cada una.
Exito!
