### ISSUE TITLE
Parte 3

### ISSUE THREAD

**Issue by CarlangaUC** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#57]
Hola!

Estuve probando con tablero de 5x5 para comparar la poda , sucede que sin poda en la ultima profundidad excede los 5 minutos y no me arroja nada, puedo poner eso en el informe? justificando obvio que con poda es mucho menor ya que en este caso si logre un resultado, en caso que no, se pueden usar mapas de menor tamaño?

Saludos.

**Comment by CarlangaUC** [comment]
Consulta adicional para no crear otra issue jaja, en la parte 3.4 cuando hablan de % de comparación, esto es respecto a una iteracion de 10 en particular para cada funcion? onda si digo que le gana en un 70% en comparación a score_circle_amount esto es equivalente a decir que si core_circle_amount gano 3 veces, tendria que ganar un 70% de veces mas que eso? , y cuando digo que gana respecto a otra, tengo que dejar constante la otra funcion a comparar ? osea, mi_funcion vs values (por ej) comparando con core_circle_amount  v/s values ?

**Comment by cstappung** [comment]
Con respecto a tu primera pregunta, esta fue contestada en #40 . Si aun te quedan dudas, no dudes en preguntar. Para tu segunda pregunta, la idea es que pongan %ganadas_funcion/iteraciones_totales. Por lo que, si gana 7 de 10, sería un 70%.

**Comment by CarlangaUC** [comment]
Consulta respecto a lo segunda, tengo que fijar una funcion para comparar? me refiero si quiero comparar score_circle_amount contra mi funcion, tendria que ver cada una respecto a values? (Para que tenga sentido la comparación segun entiendo)

**Comment by cstappung** [comment]
En el apartado 3.4 debes simular al menos 10 partidas de tu función vs score_circle_amount y que gane un 70% de las veces. Con la profundidad que desees, pero que ambos tengan la misma.
