### ISSUE TITLE
Tarea 3 - Pregunta 2

### ISSUE THREAD

**Issue by F0326** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#58]
Hola, tengo un problema con el archivo map.py porque la función colored de termcolor no se importa, a pesar de que tengo termcolor instalado.

![image](https://github.com/user-attachments/assets/e9fa9faf-bdbb-4848-bbef-60da7939bc0b)

![image](https://github.com/user-attachments/assets/3c84c9a8-56c6-4163-b1c1-3a469a999a45)

También intenté borrarlo de los paquetes y volver a instalarlo y no funcionó.

**Comment by GonzaloFuentes1** [comment]
Hola!

No había visto nunca este error. Si lo sigues manteniendo ponte en contacto conmigo para ver si lo podemos solucionar.

**Comment by ccellcynthia** [comment]
Hola, tengo el mismo problema!, cómo puedo solucionarlo?

**Comment by F0326** [comment]
Lo solucioné desinstalando termcolor y luego instalándolo con el comando

py -m pip install --upgrade termcolor
