### ISSUE TITLE
Tarea 3 parte 2 actividad 1

### ISSUE THREAD

**Issue by terecarvallo** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#59]
Hola, al correr los test me llega un mensaje que no entiendo por qué me aparece. Asi tengo el test
<img width="606" alt="Captura de pantalla 2024-10-14 a la(s) 09 05 38" src="https://github.com/user-attachments/assets/42eac8f3-5984-46fb-a0d0-f54d5b0dddb7">
Y esto es lo que me aparece en la terminal al correrlo:
 prob	  #exp	  #gen	 costo	 runtime
    1	     1	     1	- 1.00	 0.13
Traceback (most recent call last):
  File "/Users/terecarvallo/Documents/Material 2024-2/Inteligencia Artificial/t3-2024-2-terecarvallo/DCCarrera/test_map.py", line 87, in <module>
    path = [(int(c.x), int(c.y)) for c in result.trace()]
                                          ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'trace'

**Comment by GonzaloFuentes1** [comment]
Hola!

¿Hasta que actividad has desarrollado? Puede ser que estas usando las primitivas sin haberlas completado.

Saludos

**Comment by mabbottb** [comment]
A mi me esta saliendo lo mismo para la actividad 1 de la pregunta 2. A que se debe?
