### ISSUE TITLE
Tarea 2 - 1.2 "sistema computacional"

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#6]
Tengo una duda en relación a la parte 2 del ejercicio 1, sobre qué se refiere en un "sistema computacional". Se me ocurre que podría ser sistema 1 y sistema 2, pero no me calza completamente, ya que la respuesta sería demasiado obvia 😅

**Comment by tomasrodriguez1** [comment]
Tengo la misma duda!

**Comment by ignaciovilla** [comment]
Hola! 
Es parte de la pregunta esta más dirigida a que se imaginen que cosas concretas debería tener un programa computacional, para que este sea capaz de evaluar una analogía lógica. Todo esto sin considerar características humanas.
Pueden pensarlo de la siguiente forma: dadas dos situaciones, que tendría que tener un programa para que pueda decidir si son análogas.
Avísenme si eso resuelve su duda,
Mucho éxito!
