### ISSUE TITLE
T3 - Pregunta 2 - Actividad 1

### ISSUE THREAD

**Issue by KrishelC** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#60]
Hola! En la actividad se pide reportar los resultados para las cuatro heurísticas en 5 mapas con 10 problemas para cada mapa ¿es necesario reportar explícitamente los resultados de cada uno de los 10 problemas para cada mapa de las 4 heurísticas? ¿O se puede poner solamente la suma final de los resultados de los problemas para cada mapa? ¿Esto último aplica para las siguientes dos actividades?

**Comment by GonzaloFuentes1** [comment]
Hola!

Esto fue respondido en la issue 54.

Saludos
