### ISSUE TITLE
Error al correr el programa

### ISSUE THREAD

**Issue by axelaaberg** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#61]
Hola! 

De repente me ocurrió un problema muy raro donde parece que no logra importar Node. Lo he estado investigando por bastante tiempo y al final decidí empezar de nuevo pero sigo teniendo el mismo problema de todos modos.

![image](https://github.com/user-attachments/assets/1ce277df-b2f1-411c-a76d-6455e1196ecb)

![image](https://github.com/user-attachments/assets/85891944-380d-41a1-9c1c-6d39f6dad808)

![image](https://github.com/user-attachments/assets/16a9d7da-f97d-4cb1-be3f-73c289a02946)

**Comment by Hanibal24** [comment]
Te crea conflictos si tiene otra libreria llamada node (como la que se usa para java), cambia el nombre del archivo node.py a lo que quieras 
![image](https://github.com/user-attachments/assets/e9e57baa-6bdd-4a62-8a8d-059d4bbb9b18)
![image](https://github.com/user-attachments/assets/4029e530-6833-4d61-ac27-dea0707cc836)

**Comment by axelaaberg** [comment]
En efecto, muchas gracias!
