### ISSUE TITLE
Parte 2.1 error 'NoneType' object has no attribute 'trace'

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#62]
Hola! Cuando corro el test_map.py en la terminal, se me presenta el siguiente error: 
<img width="944" alt="Captura de pantalla 2024-10-14 171328" src="https://github.com/user-attachments/assets/2fe826e5-4c1f-40cd-a68c-e53b3f651272">

Como lo puedo solucionar? No he podido correr los test debido a este error, y he visto que no soy el único al que le pasa.

**Comment by GonzaloFuentes1** [comment]
Hola!

¿Hasta que actividad terminaste? El código viene solo implementado con la conectividad `int(4)` con A*.

**Comment by gaspar-mr05** [comment]
Hola. En efecto, lo que faltaba era cambiar la primitiva, ya que estaba seteada con una que no he hecho. Muchas gracias.
