### ISSUE TITLE
Formato de respuestas a actividades en parte 2 y 3

### ISSUE THREAD

**Issue by 1982739** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#63]
No me quedo claro donde se ponen las respuestas de las partes 2 y 3, ¿se escriben en el mismo código comentando?, ¿en un pdf o readme?. Gracias.

**Comment by GonzaloFuentes1** [comment]
¡Hola!

En formato .pdf es lo ideal

Saludos.
