### ISSUE TITLE
Pregunta 1 Early A*

### ISSUE THREAD

**Issue by josetomasacuna** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#65]
Hola. Tengo una duda sobre Early A*. Lo primero que me llama la atención es que Inicializamos tanto U como g(s) en infinito. Luego, en la línea: 

11. if v es objetivo and g(v) < U then: 

De alguna manera, siempre vamos a tener que realizar una comparación de infinitos . Luego entramos a: 
12. sol <- v
13. U <- g(v)  

Cambiamos U que es infinito por g(v) que es infinito. 

No deberíamos actualizar g(v) antes de hacer esta comparación?

**Comment by ignaciovilla** [comment]
Hola! Eso no va a pasar ya que cuando llegué a la linea 10 con s0, verá que la condición es falsa, por lo que saltará a la línea 14 y actualizará el valor del sucesor (o de los sucesores) de s0, luego en la siguiente iteración extraerá el estado s que tenga menor valor de open y volverá a actualizar a sus sucesores. Esto se repetirá hasta encontrar la solución.
Avísame si eso responde tu duda,
Saludos

**Comment by josetomasacuna** [comment]
Así como lo planteas tu, mi algoritmo Early A* no converge a una solución. Puede ser que necesite darle más profundidad al árbol de búsqueda, pero eso no está en las configuraciones de test_map.py. Si no actualizo el valor de U, luego de encontrar un nodo objetivo, el programa se empieza a alejar de la solución. 

Igual, si yo inserto el nodo objetivo al Open, y luego lo extraigo y  reviso los sucesores la condición de la línea 11 va a seguir siendo falsa. Tras esto estoy en una situación media rara donde el nodo objetivo está en la zona Closed.
