### ISSUE TITLE
Duda sobre nodos expandidos y generados

### ISSUE THREAD

**Issue by chocolito24** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#66]
Hola! La verdad me complica bastante el tema conceptual de los nodos expandidos y generados.
Tengo entendido que los nodos expandidos, son aquellos que extraemos de Open, pero, si actualizamos un nodo de Open y lo extraemos de nuevo, cuenta como un nuevo nodo expandido?
Los nodos generados, creo entender que se refiere a los nodos hijos de los nodos expandidos, pero me parece que esto no es correcto, ya que al avanzar en la tarea, he obtenido en varios casos más nodos expandidos que generados, lo cual no me hace mucho sentido.
Me serviría mucho si pudieran aclararme estos conceptos que me ha costado mucho entender. Muchas gracias!

**Comment by ignaciovilla** [comment]
Hola, cada nodo se expande solo una vez en el transcurso del algoritmo.
Probablemente te este pasando lo que mencionas, debido a lo mismo que fue comentado en esta issue #68 (puedes seguir la misma solución que la entregada en dicha issue).
Avísame si eso resuelve tu duda.
