### ISSUE TITLE
Tarea 3 Pregunta 2 Parte 4

### ISSUE THREAD

**Issue by chocolito24** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#67]
Hola! Estoy medio perdido con la parte donde debemos crear primitiveStraight y primitiveDiagonal.
Lo que entiendo, es que debemos generar las primitivas posibles para cada movimiento, donde por ejemplo, para primitiveStraight, debemos generar primitivas donde el movimiento sea en la misma dirección a la que se está mirando, y el costo sea acorde al movimiento. Mi problema, es que no termino de entender cómo funciona la función generate_primitive_neighbor, que me imagino que es la función que debemos usar en esta parte. Me serviría mucho saber como debiese usarse esta función, o si estoy mal enfocado jaja.
Muchas gracias!

**Comment by GonzaloFuentes1** [comment]
Hola,

No deben usar esa función. Esa es exclusiva para hacer movimientos con rotación. Por eso no les dimos tanta información acerca de ella.

Saludos

**Comment by GonzaloFuentes1** [comment]
Con respecto a lo segundo, es bastante similar a lo que estás haciendo con las conectividades 4 y 8, solo que los vecinos en este caso son las primitivas.

**Comment by chocolito24** [comment]
Buenisimo muchas gracias!
