### ISSUE TITLE
Tarea 3 Pregunta 2 Código A*

### ISSUE THREAD

**Issue by MrNachoX** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#68]
![image](https://github.com/user-attachments/assets/c878871b-a670-4dcb-ac9c-95402e07565b)

Es posible que exista un error en el if de la linea 46 del archivo astar.py?

Estuve probando con varios mapas y me tiene confundido el hecho que en la mayoría de ejecuciones los nodos expandidos sean mayores a los generados, ya que cada nodo solo se puede expandir una vez, y necesita generarse antes de expandirse. Luego noté que en el código entregado de A*, el if de la linea 46 permite generar un nuevo objeto nodo a pesar de que el estado ya se haya visto antes (debido a la segunda condicion del or) y luego se agrega se nuevo al open. Debido a este error se agregan al open multiples nodos representando el mismo estado, provocando que ese estado luego se extraiga y se expanda multiples veces.

Agradecería si me pueden aclarar este tema, ya que si elimino la segunda condición del if me hacen mucho más sentido los resultados.

**Comment by ignaciovilla** [comment]
Hola! Tienes razón, la linea 46 debería decir solo:
if is_new:
Puedes modificarlo y mencionarlo en el informe o código, pero como ya es muy tarde puedes utilizar la implementación tal cual viene.
Avísame si eso resuelve tu duda.
