### ISSUE TITLE
tarea 4 pregunta 1.4.1

### ISSUE THREAD

**Issue by AlinnaVidal** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#70]
![image](https://github.com/user-attachments/assets/8ecf5dc9-5a3a-411e-80d7-8bd7bcf8f2e5)
En el enunciado dice que debemos convertir las variables categóricas a numéricas, pero todas las columnas del archivo tienen datos numéricos. Entonces, no entiendo bien que nos piden hacer, a parte de responder las preguntas.

**Comment by jalonsoluc** [comment]
Hola!

Pongamos el siguiente ejemplo: tenemos un conjunto de datos que recopila información sobre autos. Una de las columnas, llamada `"color"`, tiene los siguientes datos: 0, 1, y 2. En este caso, 0 podría representar el color azul, 1 el color verde, y 2 el color amarillo. A la hora de entregarle estos datos al modelo, este puede interpretar, _erróneamente_, que el color amarillo es dos veces mayor que el color verde.

Volviendo a tu pregunta: a pesar de que los datos estén en un formato numérico, es necesario trabajarlos para que sus valores sean representados de la manera más fiel posible, ya que, aún siendo numéricos, **pueden no estar en un formato o escala adecuados**. La codificación/estandarización de cada columna va a depender de la característica que representa.

Saludos!
