### ISSUE TITLE
Duda Tarea 4 pregunta 2 archivos a comprimir

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#71]
Buenos días, tengo una duda respecto al formato que los archivos a comprimir deben tener, ya que el ejemplo que se muestra es relativamente corto.
¿Debe estar el archivo entero en una sola línea? (Es decir que todos los saltos de líneas son representados por \n)

Además, sobre la compresión se menciona que no necesariamente se deba disminuir el tamaño del archivo. ¿Esto significa que, en algún caso extremo, el tamaño puede aumentar? ¿O debe mantenerse como máximo del mismo tamaño?

**Comment by GonzaloFuentes1** [comment]
Hola!

Con respecto a lo primero, tu implementación debe detectar los saltos de línea puesto que el decodificador debe entregar el mismo mensaje. Así que queda a su juicio como implementarlo, recuerda justificar tu elección!

De lo segundo, en resumen si es posible que quede más pesado que el original, pero eso señala que tal vez el modelo no es el indicado para este problema. 

Saludos, quedó atento a tus comentarios!

**Comment by GonzaloFuentes1** [comment]
Hola de nuevo!

Me disculpo por el error (ya arreglado y editado), es muy importante que sigan el formato del enunciado!

Saludos!
