### ISSUE TITLE
Duda Tarea 4 pregunta 2

### ISSUE THREAD

**Issue by J0SEF4** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#72]
La verdad me enreda mucho como quieren que hagamos esta parte. ¿No entiendo que realmente debo hacer en cada archivo. ¿En dccompresor.py debo hacer un código de compresión/descompresor y en dccompresor_train.py hacer el modelo via machine learning? ¿Y luego como hago esos de los comandos? ¿Cómo los relaciono? ¿Cómo lo pruebo? ¿Creo un archivo txt con cualquier frase y lo introduzco como input a que primero el compresor o machine learning? ¿Cuál es el orden?
Perdón estoy bien enredada con que debo hacer y llevo intentando entender esto el finde. 

Gracias por adelantado y perdón las molestias.

**Comment by GonzaloFuentes1** [comment]
Hola!

En la última ayudantía compartí un esquema más o menos que yo recomiendo hacer la parte 2.

0. Entender como funcionan los compresores de texto, ver que hacen y como lo hacen. 
1. Entrenar un modelo de _Machine Learning_  que dada una ventana de caracteres previos predigan el siguiente carácter. Esto debe hacerse en `dccompresor_train.ipynb`. Se van a encontrar con problemas de como resolver los primeros caracteres, como ordenar los _inputs_ y _outputs_ del modelo, etc y se espera que ustedes propongan soluciones a todo esto (la idea es que sea menos guiado que la parte 1). Aquí se espera que obtengan un resultado y lo analicen para probar en la compresion. Como recomendación probaría varios modelos y que los guarden en un archivo `dccompresor_train.py` para que no tengamos que entrenar el modelo (o en otro formato bien claro) para la siguiente etapa.
2. Implementar el compresor: Ahora que tienen el modelo, dado un contexto pueden obtener predicciones del siguiente carácter, por lo que deben crear en el archivo `dccompresor.py` una metodología en la que unan el _output_ del modelo con un codificador de Huffman o aritmético y así codifiquen el carácter ¡La forma de unirlo es muy importante que le pongan ojo!
3. Implementar el descompresor Lo mismo que el codificador en el archivo `dccompresor.py`, pero con que los caracteres codificados pasen a su estado original.
4. Test: Deben evidenciar que su compresor en promedio hace que sus archivos sean más livianos. Si no logran conseguir que pase esto igual se considerará puntajes parciales.
5. Preguntas

Ojalá así te quede un poco más claro, quedo atento a los comentarios!
