### ISSUE TITLE
Pauta y recorrección Control Largo 1

### ISSUE THREAD

**Issue by augustayanez** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#73]
Hola! Quería saber si van a subir la pauta del control, y si va a haber proceso de recorrección. Muchas gracias!

**Comment by ignaciovilla** [comment]
Hola! 
Ya se subió la pauta y si va a haber proceso de re corrección según se informó en los anuncios de canvas.
Saludos!

**Comment by augustayanez** [comment]
Perfecto, muchas gracias!!
