### ISSUE TITLE
Pregunta 1, 1.4.2

### ISSUE THREAD

**Issue by J0SEF4** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#74]
Hola!
Tengo la duda que tantos hiperparámetros se debe definir en cada algoritmo. Pues en clases vemos que se pone 1 o 2 específicos. Pero si una va a documentación hay muchos hiperparámetros que se puede poner. Quería saber si por ejemplo en KNN es necesario solo poner el número de vecinos o poner todos sus hiperparámetros: n_neighbors, weights, algorithm, leaf_size, p, metric, metric_params?

**Comment by jalonsoluc** [comment]
Hola!

En la medida que **justifiques correctamente tu elección**, los hiperparámetros pueden ser lo que tú quieras; desde usar los hiperparámetros por defecto (es decir, instanciar el modelo sin especificar hiperparámetros), hasta tunear cada hiperparámetro que el modelo te permita.
