### ISSUE TITLE
Duda tarea 4 pregunta 2 - entrenamiento

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#75]
En el enunciado se pide que dentro del jupyter notebook

> se implemente y describa el proceso de entrenamiento y construcción del compresor/descompresor

Esto significa que el proceso de entrenamiento también debe correr en este archivo o podemos realizarlo en un archivo aparte y simplemente pegamos las funciones y añadimos una explicación en el jupyter notebook?

**Comment by ignaciovilla** [comment]
Hola! La idea de utilizar un jupyter es para que al corregir no tengamos que entrenar los modelos utilizados, por lo que el jupyter debe reflejar el entrenamiento de los modelos, esto significa que deben ejecutarse todas las celdas necesarias para hacer esto, de manera que podamos ver proceso de entrenamiento.
Avísame si eso resuelve tu duda,
Saludos

**Comment by MaxAl100** [comment]
Pero no podemos subir un modelo creado? Eso tenia entendido a partir del enunciado y lo que me respondió el profesor luego de la clase de hoy. En este caso ¿no podríamos dejar solo las explicaciones  (y los comando que hay que correr) para entrenar al predictor de caracteres?

**Comment by ignaciovilla** [comment]
Si pueden (y deben) subir el modelo entrenado. Voy a editar la respuesta anterior para clarificar.
