### ISSUE TITLE
Tarea 4 - Pregunta 2  - RAM De Colab

### ISSUE THREAD

**Issue by CrisDonosoMaass** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#76]
Hola! Estaba entrenando mi modelo en colab pero siempre se le acaba la ram antes de terminar. Hay algún problema si decido entrenarlo localmente en vez de colab?  Graciass!

**Comment by ignaciovilla** [comment]
Hola! No hay ningún problema con que lo entrenes local, mientras el Notebook que entregues tenga las celdas ejecutadas.
Se sugiere usar colab por los recursos que ofrece, pero no es obligación.
Saludos

**Comment by CrisDonosoMaass** [comment]
Buenísimo gracias!
