### ISSUE TITLE
Tarea 4 - 1.4.1: Preprocesamiento y división del dataset

### ISSUE THREAD

**Issue by GabQuiroz** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#77]
Hola, me surgió una duda respecto a la actividad 1.4.1.   

Pasa que el orden en el que piden las cosas no me hace mucho sentido. Primero, analizamos el dataset para entenderlo, luego dividimos el set de entrenamiento y pruebas y finalmente modificamos el set de datos para normalizar, eliminar valores anómalos, modificar variables categóricas, etc. pero, **¿el preprocesamiento no debería hacerse antes de dividir el set de datos en entrenamiento y pruebas?**

**Comment by jalonsoluc** [comment]
Hola!

Así es: primero se debe hacer el preprocesamiento de los datos, y luego la división en conjuntos de entrenamiento y prueba. Me percaté que, en el **enunciado**, se pide la separación y luego la estandarización/normalización; no obstante, en el **_notebook_** que les entregamos, las celdas están ordenadas de manera correcta:

<img width="1701" alt="image" src="https://github.com/user-attachments/assets/afb5aff0-9a31-4374-bf6f-4cb8b6ed10b4">

Como puedes ver, el último paso es la separación en conjuntos de entrenamiento y prueba. 

**Así que sí, estás en lo correcto; lo último que corresponde hacer es la separación.**

Saludos!

**Comment by AlvaroSotomayor** [comment]
Hola!

No se si sera un error, pero mi notebook por lo menos esta en el mismo orden del enunciado y no como en la imagen que muestras que seria en la forma correcta.

**Comment by jalonsoluc** [comment]
Mil disculpas, hubo una confusión:

La separación de los datos en conjuntos de entrenamiento y prueba se debe hacer **antes** de estandarizar/normalizar los datos, sino es posible que se introduzcan sesgos al modelo.

Saludos!

**Comment by jalonsoluc** [comment]
Otro caso para ayudarlos a entender el orden:

Al normalizar una columna, se toman en cuenta **todos los datos** que contiene. Se calculan estadísticas como la media, desviación estándar, valor mínimo/máximo, y luego se aplica la transformación a cada valor.

Digamos que una columna tiene los siguientes datos: `[1, 2, 3, 4, 5]`. Al normalizarla con `MinMaxScaler()`, quedaría algo como `[0.2, 0.4, 0.6, 0.8, 1.0]`. Luego, si la dividimos en dos, nos podría quedar algo como `[0.2, 0.4, 0.6]` y `[0.8, 1.0]`. Como pueden ver, la transformación del primer conjunto (`[1, 2, 3] -> [0.2, 0.4, 0.6]`) estuvo influenciada por la presencia de los valores `4` y `5` en el conjunto original, por lo que se considera una normalización **sesgada**.

En cambio, si dividimos los datos originales en los conjuntos `[1, 2, 3]` y `[4, 5]`, y luego aplicamos la normalización, nos quedaría algo como `[0.33, 0.67, 1.0]` y `[0, 1]`, lo cual es mucho más coherente con la idea de normalizar valores entre un rango específico (en este caso, entre 0 y 1).

Es esencial que el modelo no tenga información del conjunto de prueba durante la etapa de entrenamiento. Por ende, primero separamos los datos en conjuntos de entrenamiento y prueba, y luego los preprocesamos.

Ojalá haya quedado más claro ahora!
