### ISSUE TITLE
Acerca de modelos para ocupar en la parte 2. 

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#78]
Hola! En el enunciado de la tarea dice "En la tarea puede utilizar cualquier modelo de aprendizaje de los vistos hasta el momento en clases. No se permite el uso de modelos mas avanzados, o de modelos previamente entrenados". Esto significa que podemos utilizar modelos que no fueron vistos en clases (no se a que se refiere con "mas avanzados")? o solo podemos ocupar los vistos en clases?

**Comment by jalonsoluc** [comment]
Hola Gaspar,

Como el enunciado dice, se deben utilizar modelos de _machine learning_ **vistos en clases**. 

Un ejemplo de un modelo más avanzado sería una red neuronal profunda, lo cual no está permitido.

Saludos!
