### ISSUE TITLE
Tarea 4 Pregunta 2 Ejercicios de prueba

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#79]
Tengo una duda respecto a los ejercicios de prueba que se utilizarán para la prueba de rendimiento. ¿Serán todos en inglés? ¿En español? Ocuparán diversos idiomas? ¿O la idea es que no sepamos y nos preparemos ante todo?

**Comment by ignaciovilla** [comment]
Hola! Serán todos en inglés y están codificados en ASCII tal como los datasets que se dieron como ejemplo en el enunciado, es decir, van a usar los caracteres permitidos por ASCII.
Avísame si eso resuelve tu duda,
Saludos

**Comment by MaxAl100** [comment]
Sí, eso resuelve mi duda, muchas gracias!
