### ISSUE TITLE
Tarea 2 Ejercicio 2

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#8]
Tengo una duda general sobre el ejercicio dos, ya que se menciona en la sección "Qué debes entregar en esta parte" que 

>  cuando pedimos un algoritmo, estamos pidiendo un pseudocódigo y no una implementación detallada

Pero en el ejercicio nunca se pide presentar un algoritmo o código, entonces no me queda claro este detalle.

**Comment by ignaciovilla** [comment]
Hola! Eso quedó de una versión anterior del enunciado, no te preocupes por un pseudocódigo. Actualizaré el enunciado y lo subiré a Canvas.
Saludos
