### ISSUE TITLE
tarea 4 pregunta 2. Duda sobre peso del archivo comprimido

### ISSUE THREAD

**Issue by gaspar-mr05** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#80]
Hola. En el enunciado se dice que el siguiente formato es correcto: 0b111/0b10/0b101/.../0b11/0b1011/0b1001/0b1011. Sin embargo, me hace ruido que eso al ser bits escrito como texto, el archivo .txt final tenga un peso mayor a lo que realmente pesa el texto codificado. Sabemos que la cantidad de bytes será la cantidad de bits dividido en 8 (o eso tengo entendido), y en el caso del formato expuesto en el enunciado, el computador interpreta cada 0 y 1 o "b" como un carácter, y en ACCSI por lo menos, cada carácter es un byte. Un ejemplo sería un archivo.txt que es simplemente 0b111, este archivo pesaría 5 bytes porque son 5 caracteres, pero realmente el texto representa 3 bits (111),  y por tanto en la teoría solo son 0.5 bytes. Es esto que digo correcto?

En mi caso, mi función de codificar calcula el peso final teniendo la cantidad de bits,  y luego divide por 8 para imprimir la cantidad de  bytes en consola.

**Comment by ignaciovilla** [comment]
Hola!
