### ISSUE TITLE
Codificación de caracteres

### ISSUE THREAD

**Issue by NachoRinda** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#81]
Hola! tengo una duda acerca de cómo guardar la codificación.
Si yo uso el algoritmo de codificación de huffman debo guardar en alguna parte los bits que uso para representar cada carácter (por ej. A = 001, B=110, etc.) para después poder decodificar los mensajes. Entonces, mi duda es ¿se guarda dentro del mismo archivo <src> la codificación de cada carácter? Pregunto porque esto afectaría el peso del archivo, sin embargo, en otra issue vi que solo cuentan los bits usados para codificar el mensaje original.
Agradecería mucho si me aclararán esta duda, gracias :)

**Comment by ignaciovilla** [comment]
Hola!
No debes guardar la codificación de Huffman, por lo que el archivo codificado solo debe contener los caracteres codificados.
Te recomiendo que le des un par de vueltas más a como construir el árbol de Huffman en este caso. 
Saludos
