### ISSUE TITLE
Duda Tarea 4 pregunta 2: Demora en entrenar el modelo

### ISSUE THREAD

**Issue by axelaaberg** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#82]
Hola!

Estoy teniendo dificultades para entrenar mi modelo debido al gran tamaño de los datos y al tiempo que toma el proceso. He intentado entrenar un RandomForestClassifier, pero la cantidad de datos es demasiado grande para que mi computadora lo maneje de manera eficiente, y el proceso de entrenamiento se vuelve muy lento y ni parece que avance (usando tqdm para ver el progreso).

He considerado dividir los datos en batches y utilizar Dask para distribuir el proceso de entrenamiento, pero aún enfrento los mismos tipos de problemas. Cualquier orientación sobre cómo manejarlo de manera más efectiva sería muy útil

Saludos

**Comment by ignaciovilla** [comment]
Hola! 
Puedes probar corriendo el código en Google colab.
Por otro lado, puedes reducir la cantidad de datos de entrenamiento, lo que solo tendrá efectos en la calidad de tu modelo.
Avísame si eso te ayuda,
Saludos

**Comment by axelaaberg** [comment]
Hmm, ya intenté ajustar justamente esos aspectos, pero sin éxito. Me imagino que eso indica que hay algún otro problema detrás, pero no logro ver dónde, ya que es bastante directo.

**Comment by ignaciovilla** [comment]
Para debuggear puedes usar una sección muy pequeña de los datos, para ver si tu modelo esta efectivamente entrenando o no.

**Comment by axelaaberg** [comment]
Gracias! 

Últimas preguntas:

1) Se puede usar otros modelos de classificación como SDG classifier o solamente hay que usar Random Forest, Decision tree, SVM y KNN?

2) Cómo debo entregar mi modelo al github? Supongo que sea demasiado grande para subirlo sin modificar

**Comment by ignaciovilla** [comment]
Hola! 
1. Los vistos en clases y que sean deterministas.
2. Si github te permite subir el modelo entonces súbelo ahí, sino revisa la issue #84 
Avísame si eso soluciona tu duda.
