### ISSUE TITLE
Duda tarea 4 pregunta2: Duda estructura

### ISSUE THREAD

**Issue by matiashouston83** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#83]
Me ha estado costando la pregunta 2 y creo que es porque no estoy viendo como plantear el problema. Por ejemplo, nos dicen usar los data sets "20news" que serían los textos, pero que sería nuestra etiqueta "y" a predecir si es solo texto?

**Comment by ignaciovilla** [comment]
Hola! Eso es parte del diseño que deben hacer ustedes, pero como pista te puedo decir lo siguiente.
Lo que queremos es que el modelo dado un contexto, pueda predecir el carácter que viene a continuación de ese contexto.
Avísame si eso te ayuda.
Saludos.
