### ISSUE TITLE
Duda subir modelo a github

### ISSUE THREAD

**Issue by Maquin01** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#84]
Hola!

Mi modelo pesa 3gb y no me deja subirlo a github (por el peso). Es necesario que lo suba? se obtiene al correr el jupyter notebook pero en el enunciado dice que no se va a aceptar correr el jupyter. Que hago? Por el momento lo subiré sin el modelo dado que se entrega hoy dia y no queda tiempo. 

Estoy atento a lo que me respondan.

**Comment by benjasaldias** [comment]
Estoy en la misma situación, el mío pesa 1.3gb. Estaba intentando subirlo usando git LFS, pero no me aparece en la configuración de la repo la posibilidad de habilitar aceptar LFS.

**Comment by NachoRinda** [comment]
Me pasa lo mismo, el límite parece ser solamente 100MB :(

**Comment by benjasaldias** [comment]
@NachoRinda supuestamente el límite inicial es 1000MB pero después se settea a 100MB. Dudo que mi modelo pueda funcionar pesando tan poco xd

**Comment by ignaciovilla** [comment]
Hola! Súbanlo sin el modelo y escriban al correo oficial del curso, ahí vemos cómo resolverlo.
Mucho éxito y avísenme cualquier cosa!

**Comment by benjasaldias** [comment]
A qué correo debiera mandarlo @ignaciovilla ? El que aparece en github: ii2613.ing@uc.cl. Supuse que está mal escrito el correo (falta la c en iic), pero prefiero preguntar. Gracias!!

**Comment by ignaciovilla** [comment]
Ese es el correo!
