### ISSUE TITLE
Tarea 5 ausencia enunciado

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#86]
Buenas noches, acepté el repositorio de la tarea 5 pero solo incluye un README, no está disponible el enunciado. Revisé y tampoco está subido en canvas.

**Comment by AlvaroSotomayor** [comment]
Confirmo, no esta subido el enunciado en el Syllabus, ni en Canvas ni en el repositorio personal de la tarea...

**Comment by ignaciovilla** [comment]
Hola! Hubo un error en el link de la tarea 5. Envié nuevamente el link, avísenme si ahora pueden ver el enunciado.
Perdón por los inconvenientes 
Saludos
