### ISSUE TITLE
Tarea 2 - Duda puntuación partes 3 y 4

### ISSUE THREAD

**Issue by MaxAl100** [IIC2613-Inteligencia-Artificial-2024-2/Syllabus#9]
No me queda claro la puntuación de las partes 3 y 4.
Por una parte, la parte 3 se supone que tiene un valor de 1,5 puntos, pero cada parte (3.1, 3.2 y 3.3) dicen tener un valor de 0,3 puntos cada uno, sumando un total de 0,9. Entonces, ¿se multiplica el valor obtenido por 5/3 para que el máximo sea 1,5 o los 0,6 puntos restantes vienen de otra parte?
Además, la parte 4 no tiene una separación del puntaje, por lo que quiero saber si cada parte tiene el mismo valor, como en la parte 3 o si el valor de cada parte varía (y en cuanto).
Desde ya muchas gracias

**Comment by ignaciovilla** [comment]
Hola! Con respecto a la parte 3, cada sección tiene un puntaje de 0,5. Con respecto a la parte 4 cada sección tiene un puntaje de 0,5. Voy a actualizar el enunciado y lo subo a la carpeta de Canvas. Muchas gracias por avisar.
Saludos.
